services:
  db:
    image: postgres:18.1-alpine
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432 (for local access)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/ # Mount a named volume for persistent data

volumes:
  db_data: